---
server:
    install: '1'
    timezone: Europe/Berlin
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: selfoss, ip: 192.168.33.131, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/httpdocs
    servername: myApp.vb
sqlite:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-sqlite]

